# Generated by Django 4.2.3 on 2023-08-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_treatmentrecord_patient_delete_patient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=12)),
                ('doctor', models.CharField(max_length=12)),
                ('date', models.DateField()),
                ('department', models.CharField(max_length=12)),
                ('message', models.TextField(max_length=122)),
            ],
        ),
    ]
