# Generated by Django 4.2.3 on 2023-08-14 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_notification_inquiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='recipient',
        ),
        migrations.DeleteModel(
            name='Inquiry',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
