# Generated by Django 4.2.3 on 2023-08-14 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
