# Generated by Django 4.2.3 on 2023-08-15 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_patientinquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinquiry',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
