# Generated by Django 4.2.3 on 2023-08-16 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_patientinquiry_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinquiry',
            name='inquiry',
            field=models.TextField(max_length=100),
        ),
    ]
