# Generated by Django 4.2.3 on 2023-08-22 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_recipient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipient',
        ),
    ]
